# Generated by Django 2.2.16 on 2021-12-06 13:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='personal_phone_number',
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None),
        ),
    ]
