# Generated by Django 2.2.16 on 2021-12-06 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20211206_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='private_phone_number',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='book.Phone', verbose_name='Личный телефон сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='work_phone_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='book.Phone', verbose_name='Рабочий телефон сотрудника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
