# Generated by Django 2.2.16 on 2021-12-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20211206_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_phone_number',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='book.Phone', verbose_name='Рабочий телефон сотрудника'),
        ),
    ]
