# Generated by Django 2.2.16 on 2021-12-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20211206_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='private_phone_number',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='book.Phone', unique=True, verbose_name='Личный телефон сотрудника'),
        ),
    ]
