# Generated by Django 2.2.16 on 2021-12-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20211206_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='private_phone_number',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='book.Phone', verbose_name='Личный телефон сотрудника'),
        ),
    ]
